Repository yeongkkeul/yeongkkuel-android, pull requests merged in 2025-02, with the labels that each got.

#50 Feature/#41 채팅방 서랍 및 검색 필터링
  app/build.gradle.kts
  app/src/main/java/com/example/yeongkkuel/presentation/chat/ChatFragment.kt
  app/src/main/java/com/example/yeongkkuel/presentation/chat/ChatGroupFragment.kt
  app/src/main/java/com/example/yeongkkuel/presentation/chat/ChatMessageClickListener.kt
  app/src/main/java/com/example/yeongkkuel/presentation/chat/ChatRoomRankFragment.kt
  app/src/main/java/com/example/yeongkkuel/presentation/chat/ChatRoomRegisterFragment.kt
  app/src/main/java/com/example/yeongkkuel/presentation/chat/ChatRoomSearchFragment.kt
  app/src/main/java/com/example/yeongkkuel/presentation/chat/ChatSearchViewModel.kt
  app/src/main/java/com/example/yeongkkuel/presentation/chat/FilterAgeDialogFragment.kt
  app/src/main/java/com/example/yeongkkuel/presentation/chat/FilterExpenseDialogFragment.kt
  app/src/main/java/com/example/yeongkkuel/presentation/chat/FilterJobDialogFragment.kt
  app/src/main/java/com/example/yeongkkuel/presentation/chat/adapter/ChatGroupAdapter.kt
  app/src/main/java/com/example/yeongkkuel/presentation/chat/adapter/ChatRoomAdapter.kt
  app/src/main/java/com/example/yeongkkuel/presentation/chat/adapter/ChatRoomDrawerAdapter.kt
  app/src/main/java/com/example/yeongkkuel/presentation/chat/adapter/ChatRoomSearchAdapter.kt
  app/src/main/java/com/example/yeongkkuel/presentation/chat/dialog/ChatRoomExitDialog.kt
  app/src/main/java/com/example/yeongkkuel/presentation/chat/dialog/ChatRoomExitPartyManagerDialog.kt
  app/src/main/java/com/example/yeongkkuel/presentation/chat/dialog/ChatRoomExpelDialog.kt
  app/src/main/java/com/example/yeongkkuel/presentation/chat/dialog/ChatRoomExpelUserDialog.kt
  app/src/main/java/com/example/yeongkkuel/presentation/chat/dialog/ChatRoomExpenseAutoSendDialog.kt
  app/src/main/java/com/example/yeongkkuel/presentation/chat/dialog/ChatRoomGroupExitDialog.kt
  app/src/main/java/com/example/yeongkkuel/presentation/chat/dialog/ChatRoomProfilePartyDialog.kt
  app/src/main/java/com/example/yeongkkuel/presentation/chat/dialog/ChatRoomProfilePartyManagerDialog.kt
  app/src/main/java/com/example/yeongkkuel/presentation/chat/dialog/ChatRoomPwDialog.kt
  app/src/main/java/com/example/yeongkkuel/presentation/chat/dialog/ChatRoomRankPopup.kt
  app/src/main/java/com/example/yeongkkuel/presentation/chat/dialog/FabMenuDialog.kt
  app/src/main/res/drawable/bg_chat_modal_bottom_sheet.xml
  app/src/main/res/drawable/ic_cancel.xml
  app/src/main/res/drawable/ic_drawer_photo.xml
  app/src/main/res/drawable/ic_expel_user.xml
  app/src/main/res/layout/dialog_chat_room_exit_party_manager.xml
  app/src/main/res/layout/dialog_chat_room_expel_user.xml
  app/src/main/res/layout/dialog_chat_room_group_exit.xml
  app/src/main/res/layout/dialog_chat_room_profile_party.xml
  app/src/main/res/layout/dialog_chat_room_profile_party_manager.xml
  app/src/main/res/layout/fragment_chat_group.xml
  app/src/main/res/layout/fragment_filter_age_dialog.xml
  app/src/main/res/layout/fragment_filter_expense_dialog.xml
  app/src/main/res/layout/fragment_filter_job_dialog.xml
  app/src/main/res/layout/item_chat_room_drawer.xml
  app/src/main/res/values/arrays.xml
  app/src/main/res/values/dimens.xml
  gradle/libs.versions.toml
Labels: UI 📱, FEATURE ✨

#49 [Feature/#34] api 연결 함수 호출
  app/src/main/java/com/example/yeongkkuel/presentation/botsheet/BotSheetViewModel.kt
  app/src/main/java/com/example/yeongkkuel/presentation/stat/daily/StatDailyFragment.kt
  app/src/main/java/com/example/yeongkkuel/presentation/stat/monthly/StatMonthlyFragment.kt
  app/src/main/java/com/example/yeongkkuel/presentation/stat/monthly/StatMonthlyUiState.kt
  app/src/main/java/com/example/yeongkkuel/presentation/stat/monthly/StatMonthlyViewModel.kt
  app/src/main/java/com/example/yeongkkuel/presentation/stat/monthly/adapter/StatMonthlyCalendarListAdapter.kt
  app/src/main/java/com/example/yeongkkuel/presentation/stat/monthly/adapter/viewpager/StatMonthlyCalendarFrameFragment.kt
  app/src/main/java/com/example/yeongkkuel/presentation/stat/weekly/StatWeeklyFragment.kt
  app/src/main/java/com/example/yeongkkuel/presentation/statsettings/StatSettingsViewModel.kt
  app/src/main/java/com/example/yeongkkuel/presentation/statsettings/recommendation/StatRecommendationFragment.kt
  app/src/main/java/com/example/yeongkkuel/presentation/statsettings/recommendation/fragments/StatRecommendationSetFragment.kt
Labels: 동원, FEATURE ✨

#52 Feature/#47 약간동의 UI 수정
  app/src/main/java/com/example/yeongkkuel/presentation/base/MainActivity.kt
  app/src/main/java/com/example/yeongkkuel/presentation/my/MyFragment.kt
  app/src/main/java/com/example/yeongkkuel/presentation/signup/Term1Fragment.kt
  app/src/main/java/com/example/yeongkkuel/presentation/signup/Term2Fragment.kt
  app/src/main/java/com/example/yeongkkuel/presentation/signup/Term3Fragment.kt
  app/src/main/java/com/example/yeongkkuel/presentation/signup/Term4Fragment.kt
  app/src/main/java/com/example/yeongkkuel/presentation/signup/TermsAgreeFragment.kt
  app/src/main/java/com/example/yeongkkuel/presentation/signup/TermsViewModel.kt
  app/src/main/res/drawable/bg_terms_agree.xml
  app/src/main/res/layout/fragment_my.xml
  app/src/main/res/layout/fragment_term1.xml
  app/src/main/res/layout/fragment_term2.xml
  app/src/main/res/layout/fragment_term3.xml
  app/src/main/res/layout/fragment_term4.xml
  app/src/main/res/layout/fragment_terms_agree.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/values/strings.xml
Labels: REFACTOR ♻️, UI 📱, FEATURE ✨

#55 [refactory/#34]: bottomSheetUiState data class 변경, 그에 따른 로직 일부 수정, 주석처리
  .idea/misc.xml
  app/src/main/java/com/example/yeongkkuel/network/response/expenditure/MonthExpendituresCategory.kt
  app/src/main/java/com/example/yeongkkuel/presentation/botsheet/BotSheetCategoryListAdapter.kt
  app/src/main/java/com/example/yeongkkuel/presentation/botsheet/BotSheetHistoryListAdapter.kt
  app/src/main/java/com/example/yeongkkuel/presentation/botsheet/BotSheetUiState.kt
  app/src/main/java/com/example/yeongkkuel/presentation/botsheet/BotSheetViewModel.kt
  app/src/main/java/com/example/yeongkkuel/presentation/home/entry/ExpenseEditFragment.kt
  app/src/main/java/com/example/yeongkkuel/presentation/home/entry/ExpenseEntryFragment.kt
  app/src/main/java/com/example/yeongkkuel/presentation/home/entry/ExpenseViewFragment.kt
  app/src/main/java/com/example/yeongkkuel/presentation/stat/weekly/StatWeeklyViewModel.kt
  app/src/main/java/com/example/yeongkkuel/presentation/util/CategoryUtil.kt
Labels: 동원, REFACTOR ♻️

#56 [Feature/#34]
  app/src/main/java/com/example/yeongkkuel/network/RetrofitClient.kt
  app/src/main/java/com/example/yeongkkuel/network/StatService.kt
  app/src/main/java/com/example/yeongkkuel/network/response/expenditure/MonthExpendituresCategory.kt
  app/src/main/java/com/example/yeongkkuel/network/response/expenditure/WeekExpendituresAverage.kt
  app/src/main/java/com/example/yeongkkuel/presentation/botsheet/BotSheetUiState.kt
  app/src/main/java/com/example/yeongkkuel/presentation/botsheet/BotSheetViewModel.kt
  app/src/main/java/com/example/yeongkkuel/presentation/stat/StatFragment.kt
  app/src/main/java/com/example/yeongkkuel/presentation/stat/monthly/StatMonthlyViewModel.kt
  app/src/main/java/com/example/yeongkkuel/presentation/stat/weekly/StatWeeklyFragment.kt
  app/src/main/java/com/example/yeongkkuel/presentation/stat/weekly/StatWeeklyViewModel.kt
  app/src/main/java/com/example/yeongkkuel/presentation/statsettings/StatSettingsViewModel.kt
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_stat.xml
  app/src/main/res/layout/fragment_topbar_morebell.xml
Labels: 동원

#59 Feature/#57 - 채팅, 마이페이지 서비스 인터페이스 구현
  .idea/androidTestResultsUserPreferences.xml
  .idea/deploymentTargetSelector.xml
  .idea/other.xml
  app/src/androidTest/java/com/example/yeongkkuel/MyPageTest.kt
  app/src/main/java/com/example/yeongkkuel/network/RetrofitClient.kt
  app/src/main/java/com/example/yeongkkuel/network/request/chat/ChatPwValidateRequest.kt
  app/src/main/java/com/example/yeongkkuel/network/request/chat/ChatsRequest.kt
  app/src/main/java/com/example/yeongkkuel/network/request/mypage/DeleteMemberRequest.kt
  app/src/main/java/com/example/yeongkkuel/network/request/mypage/PatchMyPageRequest.kt
  app/src/main/java/com/example/yeongkkuel/network/response/chat/ChatDetailResult.kt
  app/src/main/java/com/example/yeongkkuel/network/response/chat/ChatMessageResponse.kt
  app/src/main/java/com/example/yeongkkuel/network/response/chat/ChatRoomInfoResult.kt
  app/src/main/java/com/example/yeongkkuel/network/response/chat/ChatSearchResult.kt
  app/src/main/java/com/example/yeongkkuel/network/response/chat/ChatSummaryResult.kt
  app/src/main/java/com/example/yeongkkuel/network/response/chat/ReceiptResult.kt
  app/src/main/java/com/example/yeongkkuel/network/response/mypage/MyPageResult.kt
  app/src/main/java/com/example/yeongkkuel/network/response/mypage/RewardsResult.kt
  app/src/main/java/com/example/yeongkkuel/network/response/mypage/UserReferralCodeResult.kt
  app/src/main/java/com/example/yeongkkuel/network/service/ChatService.kt
  app/src/main/java/com/example/yeongkkuel/network/service/MyPageService.kt
  app/src/main/java/com/example/yeongkkuel/network/service/StatService.kt
Labels: 동원, FEATURE ✨

#67 Feature/#65 - 지출 오류들 수정
  .idea/misc.xml
  app/src/main/java/com/example/yeongkkuel/network/ReissueApiService.kt
  app/src/main/java/com/example/yeongkkuel/network/data/AuthInterceptor.kt
  app/src/main/java/com/example/yeongkkuel/network/data/AuthTokenManager.kt
  app/src/main/java/com/example/yeongkkuel/network/data/TokenAuthenticator.kt
  app/src/main/java/com/example/yeongkkuel/network/response/expenditure/MonthExpendituresCalendar.kt
  app/src/main/java/com/example/yeongkkuel/network/response/expenditure/WeekExpenditureExpensesResponse.kt
  app/src/main/java/com/example/yeongkkuel/presentation/stat/StatFragment.kt
  app/src/main/java/com/example/yeongkkuel/presentation/stat/daily/StatDailyFragment.kt
  app/src/main/java/com/example/yeongkkuel/presentation/stat/monthly/StatMonthlyFragment.kt
  app/src/main/java/com/example/yeongkkuel/presentation/stat/monthly/StatMonthlyUiState.kt
  app/src/main/java/com/example/yeongkkuel/presentation/stat/monthly/StatMonthlyViewModel.kt
  app/src/main/java/com/example/yeongkkuel/presentation/stat/monthly/adapter/StatMonthlyCalendarListAdapter.kt
  app/src/main/java/com/example/yeongkkuel/presentation/stat/monthly/adapter/viewpager/StatMonthlyCalendarFrameFragment.kt
  app/src/main/java/com/example/yeongkkuel/presentation/stat/monthly/adapter/viewpager/StatMonthlyCalenderViewPagerAdapter.kt
  app/src/main/java/com/example/yeongkkuel/presentation/stat/weekly/StatWeeklyFragment.kt
  app/src/main/java/com/example/yeongkkuel/presentation/stat/weekly/StatWeeklyUiState.kt
  app/src/main/java/com/example/yeongkkuel/presentation/stat/weekly/StatWeeklyViewModel.kt
  app/src/main/java/com/example/yeongkkuel/presentation/stat/weekly/adapter/StatWeeklyCompareListAdapter.kt
  app/src/main/java/com/example/yeongkkuel/presentation/stat/weekly/adapter/StatWeeklyWeekListAdapter.kt
  app/src/main/java/com/example/yeongkkuel/presentation/util/Colors.kt
  app/src/main/res/drawable/bg_box_error.xml
  app/src/main/res/drawable/ic_error_target.xml
  app/src/main/res/drawable/ic_warning.xml
  app/src/main/res/layout/fragment_stat_daily.xml
  app/src/main/res/layout/fragment_stat_weekly.xml
  app/src/main/res/values/dimens.xml
Labels: 동원, FIX 🛠️, FEATURE ✨

#74 Feature/#73: 카테고리 목록 드래그앤드랍 기능 구현
  .idea/deploymentTargetSelector.xml
  app/src/main/java/com/example/yeongkkuel/presentation/base/MainActivity.kt
  app/src/main/java/com/example/yeongkkuel/presentation/botsheet/BotSheetViewModel.kt
  app/src/main/java/com/example/yeongkkuel/presentation/home/category/CategoryManageFragment.kt
  app/src/main/java/com/example/yeongkkuel/presentation/home/category/CategoryViewModel.kt
  app/src/main/java/com/example/yeongkkuel/presentation/home/category/adapter/CategoryAdapter.kt
  app/src/main/res/layout/fragment_expense_entry.xml
  gradle/libs.versions.toml
Labels: FEATURE ✨, 지현

#86 Feature/#41 채팅방 API 연결
  app/build.gradle.kts
  app/src/main/java/com/example/yeongkkuel/network/RetrofitClient.kt
  app/src/main/java/com/example/yeongkkuel/network/response/chat/ChatBannerResult.kt
  app/src/main/java/com/example/yeongkkuel/network/response/chat/ChatDetailResult.kt
  app/src/main/java/com/example/yeongkkuel/network/response/chat/ChatRoomRankResult.kt
  app/src/main/java/com/example/yeongkkuel/network/response/chat/ChatRoomUserResult.kt
  app/src/main/java/com/example/yeongkkuel/network/response/chat/ChatSearchResult.kt
  app/src/main/java/com/example/yeongkkuel/network/service/ChatService.kt
  app/src/main/java/com/example/yeongkkuel/presentation/chat/ChatFragment.kt
  app/src/main/java/com/example/yeongkkuel/presentation/chat/ChatGroupViewModel.kt
  app/src/main/java/com/example/yeongkkuel/presentation/chat/ChatRoom.kt
  app/src/main/java/com/example/yeongkkuel/presentation/chat/ChatRoomRegisterFragment.kt
  app/src/main/java/com/example/yeongkkuel/presentation/chat/ChatRoomSearch.kt
  app/src/main/java/com/example/yeongkkuel/presentation/chat/ChatRoomSearchClickListener.kt
  app/src/main/java/com/example/yeongkkuel/presentation/chat/ChatRoomSearchFragment.kt
  app/src/main/java/com/example/yeongkkuel/presentation/chat/ChatRoomViewModel.kt
  app/src/main/java/com/example/yeongkkuel/presentation/chat/ChatSearchViewModel.kt
  app/src/main/java/com/example/yeongkkuel/presentation/chat/adapter/ChatRoomAdapter.kt
  app/src/main/java/com/example/yeongkkuel/presentation/chat/adapter/ChatRoomDrawerAdapter.kt
  app/src/main/java/com/example/yeongkkuel/presentation/chat/adapter/ChatRoomRankAdapter.kt
  app/src/main/java/com/example/yeongkkuel/presentation/chat/adapter/ChatRoomSearchAdapter.kt
  app/src/main/java/com/example/yeongkkuel/presentation/chat/create/ChatRoomCreateFragment.kt
  app/src/main/java/com/example/yeongkkuel/presentation/chat/create/ChatRoomCreateViewModel.kt
  app/src/main/java/com/example/yeongkkuel/presentation/chat/create/SettingAgeDialogFragment.kt
  app/src/main/java/com/example/yeongkkuel/presentation/chat/create/SettingAmountPeopleDialogFragment.kt
  app/src/main/java/com/example/yeongkkuel/presentation/chat/create/SettingDailyGoalExpenseDialogFragment.kt
  app/src/main/java/com/example/yeongkkuel/presentation/chat/create/SettingJobDialogFragment.kt
  app/src/main/java/com/example/yeongkkuel/presentation/chat/data/Age.kt
  app/src/main/java/com/example/yeongkkuel/presentation/chat/data/ChatRoomRank.kt
  app/src/main/java/com/example/yeongkkuel/presentation/chat/data/Job.kt
  app/src/main/java/com/example/yeongkkuel/presentation/chat/dialog/ChatRoomProfilePartyDialog.kt
  app/src/main/java/com/example/yeongkkuel/presentation/chat/dialog/ChatRoomPwDialog.kt
  app/src/main/java/com/example/yeongkkuel/presentation/chat/network/ChatAPI.kt
  app/src/main/java/com/example/yeongkkuel/presentation/chat/network/ChatService.kt
  app/src/main/java/com/example/yeongkkuel/presentation/chat/rank/ChatRoomRankClickListener.kt
  app/src/main/java/com/example/yeongkkuel/presentation/chat/rank/ChatRoomRankFragment.kt
  app/src/main/java/com/example/yeongkkuel/presentation/chat/room/ChatGroupFragment.kt
  app/src/main/java/com/example/yeongkkuel/presentation/chat/room/ChatGroupViewModel.kt
  app/src/main/java/com/example/yeongkkuel/presentation/chat/room/ChatRoomClickListener.kt
  app/src/main/java/com/example/yeongkkuel/presentation/chat/room/ChatRoomDrawerPhotoAdapter.kt
  app/src/main/java/com/example/yeongkkuel/presentation/chat/room/ChatRoomPhotoFragment.kt
  app/src/main/java/com/example/yeongkkuel/presentation/chat/search/ChatRoomSearchClickListener.kt
  app/src/main/java/com/example/yeongkkuel/presentation/chat/search/ChatRoomSearchFragment.kt
  app/src/main/java/com/example/yeongkkuel/presentation/chat/search/ChatSearchViewModel.kt
  app/src/main/java/com/example/yeongkkuel/presentation/chat/search/FilterAgeDialogFragment.kt
  app/src/main/java/com/example/yeongkkuel/presentation/chat/search/FilterExpenseDialogFragment.kt
  app/src/main/java/com/example/yeongkkuel/presentation/chat/search/FilterJobDialogFragment.kt
  app/src/main/res/drawable/bg_chat_room_create_camera.xml
  app/src/main/res/drawable/ic_camera.xml
  app/src/main/res/layout/fragment_chat_group.xml
  app/src/main/res/layout/fragment_chat_room_create.xml
  app/src/main/res/layout/fragment_chat_room_register.xml
  app/src/main/res/layout/fragment_chat_room_search.xml
  app/src/main/res/layout/fragment_filter_amount_people_dialog.xml
  app/src/main/res/layout/fragment_filter_daily_goal_expense_dialog.xml
  app/src/main/res/layout/item_chat_room_search.xml
  app/src/main/res/navigation/nav_graph.xml
  gradle/libs.versions.toml
Labels: 승원, FEATURE ✨

#94 Fix/#90 지출 삭제 확인
  app/src/main/java/com/example/yeongkkuel/presentation/botsheet/BotSheetViewModel.kt
  app/src/main/java/com/example/yeongkkuel/presentation/home/category/CategoryDetailFragment.kt
  app/src/main/java/com/example/yeongkkuel/presentation/home/category/CategoryViewModel.kt
  app/src/main/java/com/example/yeongkkuel/presentation/home/entry/ExpenseEntryFragment.kt
  app/src/main/java/com/example/yeongkkuel/presentation/home/entry/ExpenseViewFragment.kt
  app/src/main/java/com/example/yeongkkuel/presentation/home/entry/data/ExpenseViewModel.kt
  app/src/main/java/com/example/yeongkkuel/presentation/stat/StatFragment.kt
  app/src/main/java/com/example/yeongkkuel/presentation/stat/daily/StatDailyUiState.kt
  app/src/main/java/com/example/yeongkkuel/presentation/stat/weekly/StatWeeklyFragment.kt
  app/src/main/java/com/example/yeongkkuel/presentation/stat/weekly/StatWeeklyUiState.kt
  app/src/main/java/com/example/yeongkkuel/presentation/stat/weekly/StatWeeklyViewModel.kt
  app/src/main/java/com/example/yeongkkuel/presentation/stat/weekly/adapter/StatWeeklyPieChartCategoryListAdapter.kt
  app/src/main/java/com/example/yeongkkuel/presentation/util/Colors.kt
  app/src/main/res/layout/fragment_stat_weekly.xml
Labels: 동원, FIX 🛠️

#87 Feature/#70 구글 로그인, 탈퇴
  app/src/androidTest/java/com/example/yeongkkuel/MyPageTest.kt
  app/src/main/java/com/example/yeongkkuel/network/LoginApiService.kt
  app/src/main/java/com/example/yeongkkuel/network/request/mypage/DeleteMemberRequest.kt
  app/src/main/java/com/example/yeongkkuel/network/response/login/KakaoLoginResponse.kt
  app/src/main/java/com/example/yeongkkuel/network/service/MyPageService.kt
  app/src/main/java/com/example/yeongkkuel/presentation/login/LoginFragment.kt
  app/src/main/java/com/example/yeongkkuel/presentation/my/MyFragment.kt
  app/src/main/java/com/example/yeongkkuel/presentation/my/ProfileViewModel.kt
  app/src/main/java/com/example/yeongkkuel/presentation/my/repository/ProfileRepository.kt
  app/src/main/java/com/example/yeongkkuel/presentation/my/reward/RewardFragment.kt
  app/src/main/res/layout/fragment_term1.xml
Labels: REFACTOR ♻️, FEATURE ✨

#101 Fix/#90 bottomsheet 오류, 지출 주간 차트 표시 수정
  .idea/compiler.xml
  .idea/gradle.xml
  .idea/misc.xml
  app/src/main/java/com/example/yeongkkuel/presentation/base/MainActivity.kt
  app/src/main/java/com/example/yeongkkuel/presentation/home/entry/ExpenseEntryFragment.kt
  app/src/main/java/com/example/yeongkkuel/presentation/home/entry/data/ExpenseViewModel.kt
  app/src/main/java/com/example/yeongkkuel/presentation/stat/weekly/adapter/StatWeeklyPieChartCategoryListAdapter.kt
Labels: 동원, FIX 🛠️, RELEASE 🚀

#83 Feature/#68 알림 api 연결 + 마이페이지 일부 수정
  app/src/main/java/com/example/yeongkkuel/network/RetrofitClient.kt
  app/src/main/java/com/example/yeongkkuel/network/request/notification/NotificationRequest.kt
  app/src/main/java/com/example/yeongkkuel/network/request/notification/NotificationSettingRequest.kt
  app/src/main/java/com/example/yeongkkuel/network/response/notification/NotificationDetail.kt
  app/src/main/java/com/example/yeongkkuel/network/response/notification/NotificationResult.kt
  app/src/main/java/com/example/yeongkkuel/network/service/NotificationService.kt
  app/src/main/java/com/example/yeongkkuel/presentation/home/HomeFragment.kt
  app/src/main/java/com/example/yeongkkuel/presentation/my/EditProfileFragment.kt
  app/src/main/java/com/example/yeongkkuel/presentation/my/Event.kt
  app/src/main/java/com/example/yeongkkuel/presentation/my/MyFragment.kt
  app/src/main/java/com/example/yeongkkuel/presentation/my/NotificationFragment.kt
  app/src/main/java/com/example/yeongkkuel/presentation/my/NotificationViewModel.kt
  app/src/main/java/com/example/yeongkkuel/presentation/my/ProfileViewModel.kt
  app/src/main/java/com/example/yeongkkuel/presentation/my/notification/NotificationAdapter.kt
  app/src/main/java/com/example/yeongkkuel/presentation/my/notification/data/NotificationListItem.kt
  app/src/main/java/com/example/yeongkkuel/presentation/my/reward/RewardAdapter.kt
  app/src/main/java/com/example/yeongkkuel/presentation/my/reward/RewardFragment.kt
  app/src/main/java/com/example/yeongkkuel/presentation/my/reward/RewardMapper.kt
  app/src/main/java/com/example/yeongkkuel/presentation/my/reward/data/RewardListItem.kt
  app/src/main/java/com/example/yeongkkuel/presentation/my/reward/data/RewardType.kt
  app/src/main/java/com/example/yeongkkuel/presentation/stat/StatFragment.kt
  app/src/main/res/drawable/ic_bell_off.xml
  app/src/main/res/drawable/ic_noti_dot.xml
  app/src/main/res/drawable/ic_team_goal.png
  app/src/main/res/layout/fragment_edit_profile.xml
  app/src/main/res/layout/fragment_notification.xml
  app/src/main/res/layout/fragment_topbar_morebell.xml
  app/src/main/res/layout/item_notification.xml
  app/src/main/res/layout/item_reward.xml
  app/src/main/res/layout/item_reward_header.xml
  app/src/main/res/navigation/nav_graph.xml
Labels: FEATURE ✨
