Repository yeongkkeul/yeongkkuel-android, pull requests merged in 2025-01, with the labels that each got.

#8 Feature/#7 디자인 시스템 적용
  app/src/main/ic_yeongkkuel-playstore.png
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/menu/bottom_navi_item.xml
  app/src/main/res/mipmap-hdpi/ic_yeongkkuel.webp
  app/src/main/res/mipmap-hdpi/ic_yeongkkuel_foreground.webp
  app/src/main/res/mipmap-hdpi/ic_yeongkkuel_round.webp
  app/src/main/res/mipmap-mdpi/ic_yeongkkuel.webp
  app/src/main/res/mipmap-mdpi/ic_yeongkkuel_foreground.webp
  app/src/main/res/mipmap-mdpi/ic_yeongkkuel_round.webp
  app/src/main/res/mipmap-xhdpi/ic_yeongkkuel.webp
  app/src/main/res/mipmap-xhdpi/ic_yeongkkuel_foreground.webp
  app/src/main/res/mipmap-xhdpi/ic_yeongkkuel_round.webp
  app/src/main/res/mipmap-xxhdpi/ic_yeongkkuel.webp
  app/src/main/res/mipmap-xxhdpi/ic_yeongkkuel_foreground.webp
  app/src/main/res/mipmap-xxhdpi/ic_yeongkkuel_round.webp
  app/src/main/res/mipmap-xxxhdpi/ic_yeongkkuel.webp
  app/src/main/res/mipmap-xxxhdpi/ic_yeongkkuel_foreground.webp
  app/src/main/res/mipmap-xxxhdpi/ic_yeongkkuel_round.webp
  app/src/main/res/values/colors.xml
  app/src/main/res/values/font_styles.xml
Labels: 승원, UI 📱, FEATURE ✨

#5 Feature/#3
  .idea/.name
  .idea/compiler.xml
  .idea/deploymentTargetSelector.xml
  .idea/gradle.xml
  .idea/inspectionProfiles/Project_Default.xml
  .idea/kotlinc.xml
  .idea/migrations.xml
  .idea/misc.xml
  .idea/runConfigurations.xml
  .idea/vcs.xml
  app/build.gradle.kts
  app/src/main/java/com/example/yeongkkuel/presentation/Util.kt
  app/src/main/java/com/example/yeongkkuel/presentation/stat/StatFragment.kt
  app/src/main/java/com/example/yeongkkuel/presentation/stat/StatTapModel.kt
  app/src/main/java/com/example/yeongkkuel/presentation/stat/StatViewPagerAdapter.kt
  app/src/main/java/com/example/yeongkkuel/presentation/stat/daily/StatDailyFragment.kt
  app/src/main/java/com/example/yeongkkuel/presentation/stat/daily/StatDailySpendingListAdapter.kt
  app/src/main/java/com/example/yeongkkuel/presentation/stat/daily/StatDailyUiState.kt
  app/src/main/java/com/example/yeongkkuel/presentation/stat/daily/StatDailyViewModel.kt
  app/src/main/java/com/example/yeongkkuel/presentation/stat/monthly/StatMonthlyFragment.kt
  app/src/main/java/com/example/yeongkkuel/presentation/stat/monthly/StatMonthlyViewModel.kt
  app/src/main/java/com/example/yeongkkuel/presentation/stat/weekly/StatWeeklyFragment.kt
  app/src/main/java/com/example/yeongkkuel/presentation/stat/weekly/StatWeeklyUiState.kt
  app/src/main/java/com/example/yeongkkuel/presentation/stat/weekly/StatWeeklyViewModel.kt
  app/src/main/res/drawable/bg_box_blue.xml
  app/src/main/res/drawable/bg_box_white.xml
  app/src/main/res/drawable/bg_state_bottomsheet.xml
  app/src/main/res/drawable/bg_whitecircle.xml
  app/src/main/res/drawable/ic_bell.xml
  app/src/main/res/drawable/ic_hamberger.xml
  app/src/main/res/drawable/ic_more.xml
  app/src/main/res/drawable/ic_plus_blue.xml
  app/src/main/res/drawable/ic_plus_green.xml
  app/src/main/res/drawable/ic_plus_pink.xml
  app/src/main/res/drawable/ic_title.png
  app/src/main/res/layout/fragment_stat.xml
  app/src/main/res/layout/fragment_stat_daily.xml
  app/src/main/res/layout/fragment_stat_monthly.xml
  app/src/main/res/layout/fragment_stat_weekly.xml
  app/src/main/res/layout/item_stat_daily_spending.xml
  app/src/main/res/layout/item_stat_weekly_week.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
  app/src/main/res/values/themes.xml
  gradle/libs.versions.toml
  settings.gradle.kts
Labels: 동원, UI 📱

#15 Feature/#3 지출 주간 페이지 구현
  app/src/main/java/com/example/yeongkkuel/presentation/base/MainActivity.kt
  app/src/main/java/com/example/yeongkkuel/presentation/botsheet/BotSheetCategoryListAdapter.kt
  app/src/main/java/com/example/yeongkkuel/presentation/botsheet/BotSheetHistoryListAdapter.kt
  app/src/main/java/com/example/yeongkkuel/presentation/botsheet/BotSheetItemTouchHelper.kt
  app/src/main/java/com/example/yeongkkuel/presentation/botsheet/BotSheetListener.kt
  app/src/main/java/com/example/yeongkkuel/presentation/botsheet/BotSheetUiState.kt
  app/src/main/java/com/example/yeongkkuel/presentation/botsheet/BotSheetViewModel.kt
  app/src/main/java/com/example/yeongkkuel/presentation/stat/StatFragment.kt
  app/src/main/java/com/example/yeongkkuel/presentation/stat/ViewPagerTouchListener.kt
  app/src/main/java/com/example/yeongkkuel/presentation/stat/daily/StatDailyFragment.kt
  app/src/main/java/com/example/yeongkkuel/presentation/stat/monthly/StatMonthlyFragment.kt
  app/src/main/java/com/example/yeongkkuel/presentation/stat/weekly/StatWeeklyFragment.kt
  app/src/main/java/com/example/yeongkkuel/presentation/stat/weekly/StatWeeklyUiState.kt
  app/src/main/java/com/example/yeongkkuel/presentation/stat/weekly/StatWeeklyWeekListAdapter.kt
  app/src/main/java/com/example/yeongkkuel/presentation/stat/weekly/adapter/StatWeeklyCompareListAdapter.kt
  app/src/main/java/com/example/yeongkkuel/presentation/stat/weekly/adapter/StatWeeklyPieChartCategoryListAdapter.kt
  app/src/main/java/com/example/yeongkkuel/presentation/stat/weekly/adapter/StatWeeklyWeekListAdapter.kt
  app/src/main/java/com/example/yeongkkuel/presentation/statbotsheet/StatBotSheetUiState.kt
  app/src/main/java/com/example/yeongkkuel/presentation/statbotsheet/StatBotSheetViewModel.kt
  app/src/main/java/com/example/yeongkkuel/presentation/util/Colors.kt
  app/src/main/java/com/example/yeongkkuel/presentation/util/SpendingCategory.kt
  app/src/main/java/com/example/yeongkkuel/presentation/util/Util.kt
  app/src/main/res/drawable/bg_box_lightpurple.xml
  app/src/main/res/drawable/bg_box_strok_lightpurple.xml
  app/src/main/res/drawable/bg_point_blue.xml
  app/src/main/res/drawable/bg_point_green.xml
  app/src/main/res/drawable/bg_point_pink.xml
  app/src/main/res/drawable/bg_point_today.xml
  app/src/main/res/drawable/ic_point_down.xml
  app/src/main/res/drawable/ic_point_up.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_stat_daily.xml
  app/src/main/res/layout/fragment_stat_weekly.xml
  app/src/main/res/layout/item_stat_weekly_compare.xml
  app/src/main/res/layout/item_stat_weekly_piechartcategory.xml
  app/src/main/res/layout/item_stat_weekly_week.xml
  app/src/main/res/values/dimens.xml
Labels: 동원, UI 📱, FEATURE ✨

#17 Feature/#6 온보딩
  .idea/appInsightsSettings.xml
  .idea/deploymentTargetSelector.xml
  .idea/misc.xml
  .idea/vcs.xml
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/yeongkkuel/presentation/base/MainActivity.kt
  app/src/main/java/com/example/yeongkkuel/presentation/home/HomeFragment.kt
  app/src/main/java/com/example/yeongkkuel/presentation/login/LoginFragment.kt
  app/src/main/java/com/example/yeongkkuel/presentation/login/YeongKkuelApplication.kt
  app/src/main/java/com/example/yeongkkuel/presentation/signup/SignupFragment.kt
  app/src/main/java/com/example/yeongkkuel/presentation/splash/SplashFragment.kt
  app/src/main/res/anim/slide_in_up.xml
  app/src/main/res/anim/slide_up.xml
  app/src/main/res/drawable/bg_button_gray.xml
  app/src/main/res/drawable/bg_button_purple.xml
  app/src/main/res/drawable/bg_dialog_background.xml
  app/src/main/res/drawable/bg_recommend.xml
  app/src/main/res/drawable/btn_sucess.xml
  app/src/main/res/drawable/google_button_selector.xml
  app/src/main/res/drawable/ic_back.xml
  app/src/main/res/drawable/ic_coin.png
  app/src/main/res/drawable/ic_dummy_splash.xml
  app/src/main/res/drawable/ic_google_logo.png
  app/src/main/res/drawable/ic_kakao_logo.png
  app/src/main/res/drawable/ic_splash_logo.png
  app/src/main/res/drawable/kakao_button_selector.xml
  app/src/main/res/drawable/rounded_nickname_background.xml
  app/src/main/res/drawable/rounded_nickname_background_error.xml
  app/src/main/res/layout/dialog_recommend_code.xml
  app/src/main/res/layout/dialog_reward.xml
  app/src/main/res/layout/fragment_login.xml
  app/src/main/res/layout/fragment_signup.xml
  app/src/main/res/layout/fragment_splash.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
  gradle.properties
  settings.gradle.kts
Labels: 유찬, UI 📱, FEATURE ✨

#18 hotfix: 코드 중복 제거 및 nav 연결
  app/src/main/java/com/example/yeongkkuel/presentation/base/MainActivity.kt
Labels: FIX 🛠️

#19 Feature/#3 지출 월간 뼈대 구현
  .idea/deploymentTargetSelector.xml
  app/src/main/java/com/example/yeongkkuel/presentation/botsheet/BotSheetUiState.kt
  app/src/main/java/com/example/yeongkkuel/presentation/stat/StatFragment.kt
  app/src/main/java/com/example/yeongkkuel/presentation/stat/daily/StatDailyFragment.kt
  app/src/main/java/com/example/yeongkkuel/presentation/stat/monthly/StatMonthlyFragment.kt
  app/src/main/java/com/example/yeongkkuel/presentation/stat/monthly/StatMonthlyUiState.kt
  app/src/main/java/com/example/yeongkkuel/presentation/stat/monthly/StatMonthlyViewModel.kt
  app/src/main/java/com/example/yeongkkuel/presentation/stat/monthly/adapter/StatMonthlyCalendarListAdapter.kt
  app/src/main/java/com/example/yeongkkuel/presentation/stat/monthly/adapter/viewpager/StatMonthlyCalendarFrameFragment.kt
  app/src/main/java/com/example/yeongkkuel/presentation/stat/monthly/adapter/viewpager/StatMonthlyCalenderViewPagerAdapter.kt
  app/src/main/java/com/example/yeongkkuel/presentation/stat/weekly/StatWeeklyFragment.kt
  app/src/main/java/com/example/yeongkkuel/presentation/stat/weekly/StatWeeklyUiState.kt
  app/src/main/java/com/example/yeongkkuel/presentation/stat/weekly/adapter/StatWeeklyPieChartCategoryListAdapter.kt
  app/src/main/java/com/example/yeongkkuel/presentation/util/Week.kt
  app/src/main/res/drawable/bg_box_statmonthlytextbox.xml
  app/src/main/res/layout/fragment_stat.xml
  app/src/main/res/layout/fragment_stat_monthly.xml
  app/src/main/res/layout/item_calendar_day.xml
  app/src/main/res/layout/item_calendar_dayofweek.xml
  app/src/main/res/layout/item_calender_frame.xml
  app/src/main/res/layout/item_unknown.xml
  app/src/main/res/navigation/nav_graph.xml
Labels: 동원, UI 📱, FEATURE ✨

#21 Feature/#6
  app/build.gradle.kts
  app/src/main/java/com/example/yeongkkuel/presentation/base/MainActivity.kt
  app/src/main/java/com/example/yeongkkuel/presentation/login/LoginFragment.kt
  app/src/main/java/com/example/yeongkkuel/presentation/signup/SignupFragment.kt
  app/src/main/java/com/example/yeongkkuel/presentation/signup/TermsAgreeFragment.kt
  app/src/main/res/drawable/bg_signup_btn_checked.xml
  app/src/main/res/drawable/bg_signup_btn_default.xml
  app/src/main/res/drawable/bg_signup_btn_disabled.xml
  app/src/main/res/drawable/ic_big_checkbox_checked.xml
  app/src/main/res/drawable/ic_big_checkbox_unchecked.xml
  app/src/main/res/drawable/ic_small_checkbox_checked.xml
  app/src/main/res/drawable/ic_small_checkbox_unchecked.xml
  app/src/main/res/drawable/selector_big_checkbox.xml
  app/src/main/res/drawable/selector_signup_button.xml
  app/src/main/res/drawable/selector_small_checkbox.xml
  app/src/main/res/layout/fragment_signup.xml
  app/src/main/res/layout/fragment_terms_agree.xml
  app/src/main/res/navigation/nav_graph.xml
  gradle/libs.versions.toml
Labels: 유찬, FEATURE ✨

#25 [Feature/#3] 지출액 설정, 지출액 추천 화면 구현
  .idea/misc.xml
  app/src/main/java/com/example/yeongkkuel/presentation/base/MainActivity.kt
  app/src/main/java/com/example/yeongkkuel/presentation/botsheet/BotSheetCategoryListAdapter.kt
  app/src/main/java/com/example/yeongkkuel/presentation/botsheet/BotSheetListener.kt
  app/src/main/java/com/example/yeongkkuel/presentation/stat/StatFragment.kt
  app/src/main/java/com/example/yeongkkuel/presentation/stat/StatViewPagerAdapter.kt
  app/src/main/java/com/example/yeongkkuel/presentation/stat/monthly/StatMonthlyFragment.kt
  app/src/main/java/com/example/yeongkkuel/presentation/stat/weekly/StatWeeklyFragment.kt
  app/src/main/java/com/example/yeongkkuel/presentation/stat/weekly/StatWeeklyViewModel.kt
  app/src/main/java/com/example/yeongkkuel/presentation/stat/weekly/adapter/StatWeeklyCompareListAdapter.kt
  app/src/main/java/com/example/yeongkkuel/presentation/stat/weekly/adapter/StatWeeklyWeekListAdapter.kt
  app/src/main/java/com/example/yeongkkuel/presentation/statsettings/StatSettingsUiState.kt
  app/src/main/java/com/example/yeongkkuel/presentation/statsettings/StatSettingsViewModel.kt
  app/src/main/java/com/example/yeongkkuel/presentation/statsettings/recommendation/StatRecommendationFragment.kt
  app/src/main/java/com/example/yeongkkuel/presentation/statsettings/recommendation/adapter/StatRecommendationViewPagerAdapter.kt
  app/src/main/java/com/example/yeongkkuel/presentation/statsettings/recommendation/fragments/StatRecommendationInputAverageFragment.kt
  app/src/main/java/com/example/yeongkkuel/presentation/statsettings/recommendation/fragments/StatRecommendationRatioFragment.kt
  app/src/main/java/com/example/yeongkkuel/presentation/statsettings/recommendation/fragments/StatRecommendationSetFragment.kt
  app/src/main/java/com/example/yeongkkuel/presentation/statsettings/settings/StatSettingsFragment.kt
  app/src/main/java/com/example/yeongkkuel/presentation/util/EtUtil.kt
  app/src/main/java/com/example/yeongkkuel/presentation/util/NavUtil.kt
  app/src/main/java/com/example/yeongkkuel/presentation/util/Util.kt
  app/src/main/res/color/tab_stat_text.xml
  app/src/main/res/drawable/bg_box_black0.xml
  app/src/main/res/drawable/bg_box_main1.xml
  app/src/main/res/drawable/bg_btn_no.xml
  app/src/main/res/drawable/bg_btn_yes.xml
  app/src/main/res/drawable/bg_oval.xml
  app/src/main/res/drawable/bg_progressbar.xml
  app/src/main/res/drawable/bg_toggle_stat_recommend.xml
  app/src/main/res/drawable/check.xml
  app/src/main/res/drawable/check_not.xml
  app/src/main/res/drawable/ic_add.xml
  app/src/main/res/drawable/ic_left_arrow.xml
  app/src/main/res/drawable/ic_logo.png
  app/src/main/res/layout/fragment_stat.xml
  app/src/main/res/layout/fragment_stat_recommendation.xml
  app/src/main/res/layout/fragment_stat_settings.xml
  app/src/main/res/layout/item_botsheet_category.xml
  app/src/main/res/layout/item_stat_recommendation_input_average.xml
  app/src/main/res/layout/item_stat_recommendation_ratio.xml
  app/src/main/res/layout/item_stat_recommendation_setting.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/values/font_styles.xml
  app/src/main/res/values/styles.xml
Labels: 동원, FIX 🛠️, UI 📱

#29 [Feature/#27]
  app/src/main/java/com/example/yeongkkuel/presentation/botsheet/BotSheetUiState.kt
  app/src/main/java/com/example/yeongkkuel/presentation/botsheet/BotSheetViewModel.kt
  app/src/main/java/com/example/yeongkkuel/presentation/network/RetrofitClient.kt
  app/src/main/java/com/example/yeongkkuel/presentation/network/YeongkkuelService.kt
  app/src/main/java/com/example/yeongkkuel/presentation/network/request/expenditure/ExpenditureTargetRequest.kt
  app/src/main/java/com/example/yeongkkuel/presentation/network/response/expenditure/MonthExpendituresCalendar.kt
  app/src/main/java/com/example/yeongkkuel/presentation/network/response/expenditure/MonthExpendituresCategory.kt
  app/src/main/java/com/example/yeongkkuel/presentation/network/response/expenditure/MonthlyAverageExpenditureResponse.kt
  app/src/main/java/com/example/yeongkkuel/presentation/network/response/expenditure/WeekExpenditureExpensesResponse.kt
  app/src/main/java/com/example/yeongkkuel/presentation/network/response/expenditure/WeekExpendituresAverage.kt
  app/src/main/java/com/example/yeongkkuel/presentation/stat/daily/StatDailyFragment.kt
  app/src/main/java/com/example/yeongkkuel/presentation/stat/monthly/StatMonthlyViewModel.kt
  app/src/main/java/com/example/yeongkkuel/presentation/stat/weekly/StatWeeklyFragment.kt
  app/src/main/java/com/example/yeongkkuel/presentation/stat/weekly/StatWeeklyUiState.kt
  app/src/main/java/com/example/yeongkkuel/presentation/stat/weekly/StatWeeklyViewModel.kt
  app/src/main/java/com/example/yeongkkuel/presentation/statsettings/StatSettingsUiState.kt
  app/src/main/java/com/example/yeongkkuel/presentation/statsettings/StatSettingsViewModel.kt
  app/src/main/java/com/example/yeongkkuel/presentation/statsettings/recommendation/fragments/StatRecommendationInputAverageFragment.kt
  app/src/main/java/com/example/yeongkkuel/presentation/util/Colors.kt
  app/src/main/java/com/example/yeongkkuel/presentation/util/SpendingCategory.kt
  app/src/main/java/com/example/yeongkkuel/presentation/util/Week.kt
  app/src/main/res/layout/fragment_stat_weekly.xml
Labels: 동원, FEATURE ✨

#30 Feature/#22 마이페이지
  app/src/main/java/com/example/yeongkkuel/presentation/my/DailyExpenseGoalFragment.kt
  app/src/main/java/com/example/yeongkkuel/presentation/my/EditProfileFragment.kt
  app/src/main/java/com/example/yeongkkuel/presentation/my/MyFragment.kt
  app/src/main/java/com/example/yeongkkuel/presentation/my/MyPageApiService.kt
  app/src/main/java/com/example/yeongkkuel/presentation/my/NotificationFragment.kt
  app/src/main/java/com/example/yeongkkuel/presentation/my/ProfileViewModel.kt
  app/src/main/java/com/example/yeongkkuel/presentation/my/data/UserProfileRequest.kt
  app/src/main/java/com/example/yeongkkuel/presentation/my/data/UserProfileResponse.kt
  app/src/main/java/com/example/yeongkkuel/presentation/my/data/UserProfileResult.kt
  app/src/main/java/com/example/yeongkkuel/presentation/my/notification/NotificationAdapter.kt
  app/src/main/java/com/example/yeongkkuel/presentation/my/notification/data/NotificationItem.kt
  app/src/main/java/com/example/yeongkkuel/presentation/my/notification/data/NotificationType.kt
  app/src/main/java/com/example/yeongkkuel/presentation/my/reward/RewardAdapter.kt
  app/src/main/java/com/example/yeongkkuel/presentation/my/reward/RewardFragment.kt
  app/src/main/java/com/example/yeongkkuel/presentation/my/reward/data/RewardItem.kt
  app/src/main/java/com/example/yeongkkuel/presentation/my/reward/data/RewardType.kt
  app/src/main/res/drawable/bg_my_box.xml
  app/src/main/res/drawable/bg_my_description.xml
  app/src/main/res/drawable/bg_my_edit_shadow.xml
  app/src/main/res/drawable/bg_my_withdraw.xml
  app/src/main/res/drawable/bg_my_withdraw_checked.xml
  app/src/main/res/drawable/bg_my_withdraw_default.xml
  app/src/main/res/drawable/bg_my_withdraw_disabled.xml
  app/src/main/res/drawable/bg_profile_edit.xml
  app/src/main/res/drawable/ic_challenge_join.xml
  app/src/main/res/drawable/ic_coin_small.png
  app/src/main/res/drawable/ic_copy.xml
  app/src/main/res/drawable/ic_daily_exceed.xml
  app/src/main/res/drawable/ic_my_look_foward.xml
  app/src/main/res/drawable/ic_my_profile.png
  app/src/main/res/drawable/ic_my_reward_detail.xml
  app/src/main/res/drawable/ic_no_spend_reward.xml
  app/src/main/res/drawable/ic_ranking_reward.xml
  app/src/main/res/drawable/ic_ranking_update.xml
  app/src/main/res/drawable/ic_small_checkbox_checked.xml
  app/src/main/res/drawable/ic_small_checkbox_unchecked.xml
  app/src/main/res/drawable/selector_button.xml
  app/src/main/res/layout/dialog_logout.xml
  app/src/main/res/layout/dialog_my_recommend_code.xml
  app/src/main/res/layout/dialog_withdraw.xml
  app/src/main/res/layout/dialog_withdraw_detail.xml
  app/src/main/res/layout/fragment_daily_expense_goal.xml
  app/src/main/res/layout/fragment_edit_profile.xml
  app/src/main/res/layout/fragment_my.xml
  app/src/main/res/layout/fragment_notification.xml
  app/src/main/res/layout/fragment_reward.xml
  app/src/main/res/layout/item_notification.xml
  app/src/main/res/layout/item_notification_header.xml
  app/src/main/res/layout/item_reward.xml
  app/src/main/res/layout/item_reward_header.xml
  app/src/main/res/navigation/nav_graph.xml
Labels: 유찬, FEATURE ✨

#37 Fix/#36 - 빌드 오류 해결
  app/src/main/java/com/example/yeongkkuel/presentation/botsheet/BotSheetViewModel.kt
  app/src/main/java/com/example/yeongkkuel/presentation/stat/weekly/StatWeeklyViewModel.kt
  app/src/main/java/com/example/yeongkkuel/presentation/util/Colors.kt
  app/src/main/java/com/example/yeongkkuel/presentation/util/SpendingCategory.kt
Labels: FIX 🛠️

#40 feature/#4: 빌드 오류 및 불필요한 코드 제거
  .idea/appInsightsSettings.xml
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/yeongkkuel/YeongKkuelApplication.kt
  app/src/main/java/com/example/yeongkkuel/presentation/login/LoginFragment.kt
  app/src/main/java/com/example/yeongkkuel/presentation/login/YeongKkuelApplication.kt
  app/src/main/java/com/example/yeongkkuel/presentation/stat/StatFragment.kt
  app/src/main/java/com/example/yeongkkuel/presentation/stat/monthly/StatMonthlyFragment.kt
  app/src/main/res/values/colors.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
  gradle/libs.versions.toml
Labels: 승원, FIX 🛠️

#39 [Feature/#34] 지출 달력 로직, http 네트워크 보안 허용
  .idea/gradle.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/yeongkkuel/presentation/network/RetrofitClient.kt
  app/src/main/java/com/example/yeongkkuel/presentation/network/YeongkkuelService.kt
  app/src/main/java/com/example/yeongkkuel/presentation/network/response/expenditure/MonthExpendituresCalendar.kt
  app/src/main/java/com/example/yeongkkuel/presentation/stat/monthly/StatMonthlyViewModel.kt
  app/src/main/java/com/example/yeongkkuel/presentation/statsettings/StatSettingsViewModel.kt
  app/src/main/java/com/example/yeongkkuel/presentation/util/Util.kt
  app/src/main/res/xml/network_security_config.xml
Labels: 동원, FEATURE ✨
